"""updated column

Revision ID: 3c1c038bacb1
Revises: 4b79978cebad
Create Date: 2026-08-30 12:54:22.663891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c1c038bacb1'
down_revision: Union[str, Sequence[str], None] = '4b79978cebad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('metadata', sa.JSON(), nullable=True))
    op.drop_column('audit_logs', 'details')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('audit_logs', 'metadata')
    # ### end Alembic commands ###
