"""removed created by column

Revision ID: 47e910b35a8d
Revises: f515b873969a
Create Date: 2026-08-29 22:31:46.409351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47e910b35a8d'
down_revision: Union[str, Sequence[str], None] = 'f515b873969a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('expenses_created_by_fkey'), 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('expenses_created_by_fkey'), 'expenses', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###
